# Generated by Django 5.0.7 on 2024-07-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('main_text', models.TextField(max_length=10000, verbose_name='Содержание')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
