# Generated by Django 5.0.7 on 2024-08-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('commentary', models.TextField(max_length=500, verbose_name='Содержание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='firsttable',
            options={'verbose_name': 'рыба', 'verbose_name_plural': 'рыбы'},
        ),
        migrations.AddField(
            model_name='firsttable',
            name='img',
            field=models.FileField(null=True, upload_to='img/', verbose_name='картинка'),
        ),
    ]
