# Generated by Django 5.0.7 on 2024-09-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_commentaries_alter_firsttable_options_firsttable_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaries',
        ),
    ]
